name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Format, Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Format
        run: make format

      - name: Build
        run: make build

      - name: Test
        run: make test
